# Generated by Django 4.1.7 on 2023-02-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='bot_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='текущее состояния бота'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='telegram_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='telegram Id'),
        ),
    ]
