# Generated by Django 4.1.7 on 2023-02-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0004_alter_botuser_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
    ]
