# Generated by Django 4.1.7 on 2023-02-15 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0006_systemsettings_botuser_created_at_tariff_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('botuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='support_app.botuser')),
            ],
            options={
                'verbose_name': 'владелец',
                'verbose_name_plural': 'владельцы',
            },
            bases=('support_app.botuser',),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='role',
            field=models.CharField(choices=[('Клиент', 'Client'), ('Подрядчик', 'Contractor'), ('Менеджер', 'Manager'), ('Владелец', 'Owner')], max_length=30, verbose_name='роль'),
        ),
    ]
