# Generated by Django 4.1.7 on 2023-02-18 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0008_order_creds_order_estimated_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='all_contractors_informed',
            field=models.BooleanField(default=False, verbose_name='все подрядчики проинформированы'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_contractors_informed',
            field=models.BooleanField(default=False, verbose_name='закрепленные подрядчики проинформированы'),
        ),
        migrations.CreateModel(
            name='AssignedContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contractors', to='support_app.client')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clients', to='support_app.contractor')),
            ],
        ),
    ]
